### ISSUE TITLE
addon/color not find

### ISSUE THREAD

**Issue by MustafaUnluCodes** [heybokeh/pollen#54]
it seems

color addon not working.

Failed to find 'pollen-css/addons/colors.css'

I tried with cdn and also with npm install.

**Comment by madeleineostoja** [comment]
Hi there, what version are you using? The addon CSS files have been deprecated in `v4.0.0-rc.1`, where they're replaced with a config file. Make sure you install the `@latest` version rather than the rc, which should resolve to `v3.1.1`
