### ISSUE TITLE
Support shadow DOM

### ISSUE THREAD

**Issue by jakobrosenberg** [heybokeh/pollen#59]
Currently variables are generated in this fashion:

```css
:root {
  --scale-0: 1rem;
  --scale-1: 1.125rem;
  --scale-2: 1.25rem;
  --scale-3: 1.5rem;
  --scale-4: 1.875rem;
  --scale-5: 2.25rem;
  --scale-6: 3rem;
  --scale-7: 3.75rem;
  --scale-8: 4.5rem;
  ``` 

Would it be possible to omit `:root {` to support scoped usage? Eg. in shadow DOM.

**Comment by jakobrosenberg** [comment]
Upon further reading, it seems `:host {` is recommended over `:root {` for this very reason.

**Comment by madeleineostoja** [comment]
Ah okay good catch. Is :host supported in all evergreens, and functionally the same as :root outside shadow dom? If so happy to accept a PR. Definitely keen to support shadow dom if there’s no cost to the majority use case.

Otherwise it’d be trivial to make the selector used configurable, which might be a good idea regardless actually, no matter what default we ship

**Comment by jakobrosenberg** [comment]
Only IE doesn't like it. https://caniuse.com/?search=%3Ahost

The only difference between `:root` and `:host` AFAIK is that the latter is scoped to the element where it's used.

**Comment by madeleineostoja** [comment]
In that case it wouldn’t work in shadow dom anyway would it? Because the :host would be global? I don’t really know though, I’d need to test.

I think a good first step would be making the selector configurable, but only if there’s value in it. At least it would be a non-breaking change

**Comment by jakobrosenberg** [comment]
The `:host` option works in shadow DOM just like it would outside of it. That's how I'm using Pollen. I copy pasted the css and changed `:root` to `:host`. Unfortunately that prevents me from using CDN, which is why I opened this issue. 😅

![image](https://user-images.githubusercontent.com/4153004/148042110-29eb53d3-8674-4b55-a2c7-bd7438e9e198.png)

**Comment by madeleineostoja** [comment]
Gotcha, didn’t realise you could link a style sheet in shadow dom. You’d still need to duplicate that link in every shadow root, but I’d that’s workable happy to support it. 

Opening up the selector used as a config option would make this a non-breaking change, but not sure if that config is actually useful or if it’s just noise. So might be better to just change to host if there are absolutely zero ramifications or differences outside shadow dom

**Comment by jakobrosenberg** [comment]
I would consider it a breaking change since there's a theoretical possibility that someone could be loading pollen inside an element without the intention of scoping it.

The solution to that scenario is to load `pollen` where you need it. For 99% that would be in `html`->`head`->`link`.

https://css-tricks.com/saving-the-day-with-scoped-css/
