### ISSUE TITLE
Feature: Add ability to export json file of tokens

### ISSUE THREAD

**Issue by ItsMeAra** [heybokeh/pollen#61]
Currently the official docs site is the only place you could see a list of all available tokens and their values and if you customize any of them, this would no longer stay in sync with the officially supported tokens.

By adding the ability to export a JSON (or yaml?) file with all customizations applied, you would be able to use this JSON output to generate your own dictionary reference/docs site so that your entire team can now stay in sync. It would also make it easier to build out utility classes out of the tokens as you could convert JSON to SCSS easily with existing packages.

Perhaps something like this in the config file? 

```
module.exports = {
  outputjson: 'some/path/pollen.json',
  modules: {
    // Module config
  }
}
``` 

Example output could be something like:

```
{
  "size": {
    "0": "2px",
    "1": "4px",
    "2": "8px",
    "3": "12px"
  },

  "blur": {
    "sm": "blur(4px)",
    "md": "blur(8px)",
    "lg": "blur(16px)",
    "xl": "blur(24px)",
    "2xl": "blur(40px)"
  }
}
```

**Comment by madeleineostoja** [comment]
This is a great idea and something that would be fairly easy to implement. Happy to accept a PR or I'll get to it when I can.

I'm not 100% on the config option name, maybe `schema:`? Since that's kind of what it is, even though we'd be kind of hijacking the term.

**Comment by ItsMeAra** [comment]
I'm horrible at naming things 😂 Schema works, unless someone has a better idea.

**Comment by madeleineostoja** [comment]
How about we just add a check for string vs object on the existing `output` option:

**CSS only**
```js
{ 
  output: './pollen.css'
}
```

**CSS + JSON schema**
```js
{
  output: {
    css: './pollen.css',
    schema: './pollen.json'
  }
}
```

`css` could also be named `variables`, but I think `css` is clearer

**Comment by ItsMeAra** [comment]
I like it!

![Batman approves](http://i.giphy.com/FbZYCW78PANyM.gif)
