### ISSUE TITLE
Add and configure unit tests 

### ISSUE THREAD

**Issue by shannonrothe** [heybokeh/pollen#67]
It would be cool to be able to write tests against PRs for this project and I noticed `jest` isn't setup yet! Happy to take some time to look into this one if somebody doesn't get to it before me 👍🏼

**Comment by madeleineostoja** [comment]
Yep unit testing is definitely something I’ve been meaning to get to now that there’s logic around the config / css generation. Jest is a good option, and I’m partial to uvu as well, but not that fussed on what we go with they’re all much of a muchness.

**Comment by shannonrothe** [comment]
Sounds good – I'm not too sold on Jest anyway, it's a bit of a pain to setup with ESM/TypeScript. Perhaps [Vitest](https://vitest.dev) is an option too? 👀
