### ISSUE TITLE
Fluid sizes

### ISSUE THREAD

**Issue by enyo** [heybokeh/pollen#73]
I've been using Pollen for the last 2 weeks and it's amazing.

I think that one addition that would be nice is a fluid sizing system. I've seen the same in [Open Props](https://open-props.style/#typography) although I think that their implementation is not great.

I know that I can configure fluid sizes myself, but it would be really great to have them out of the box since I think this is a good pattern that should be encouraged.

The Open Props implementation is very simple:

```css
  --font-size-fluid-0: clamp(.75rem, 2vw, 1rem);
  --font-size-fluid-1: clamp(1rem, 4vw, 1.5rem);
  --font-size-fluid-2: clamp(1.5rem, 6vw, 2.5rem);
  --font-size-fluid-3: clamp(2rem, 9vw, 3.5rem);
```

but I think that this is too simple, since this means that fonts will shrink at different speeds and reach their min and max at different viewport widths.

What I have been using is based on [this css-tricks article](https://css-tricks.com/linearly-scale-font-size-with-css-clamp-based-on-the-viewport/) and it works perfectly. The downside with this method is, that it's not possible to use the `--scale-X` custom properties in CSS because it involves doing some math that can't be done with `<dimension>` types.

I'm not 100% sure how to solve this best, but one suggestion would be to add a `linearClamp` function that takes a viewport min and max width in px and a size min and max in rem and spits out the `clamp([...])` property. This can then be used to generate the default values in `pollen.css` but also by users of the library to generate their own fluid sizes.

What do you think? If you like this idea I can create a PR to discuss this further.

**Comment by madeleineostoja** [comment]
Hey so I actually wrote a fairly popular postcss plug-in aaaaages ago that implements this (https://github.com/madeleineostoja/postcss-responsive-type, ported to css-in-js in https://github.com/madeleineostoja/satchel) so I’m across the concept. Idk how it would fit into pollen though, even if you exported a function like that you couldn’t just apply it with a CSS variable, which breaks Pollens very straightforward abstraction.

Open to ideas but I think this is better implemented in user land with a mixin/function/processor plug-in, etc

**Comment by enyo** [comment]
@madeleineostoja oh that's great. The plugin looks really interesting.

I completely agree that adding more API surface needs to be done thoughtfully, but I think that adding some kind of fluid system could be worth it.

With a `clamp` function it can just be limited to a single custom property. If you're worried about exposing a function to do this, maybe an approach would be to add fluid font sizes in a first step without exposing the JS function that allows generating them? ... but then again it's annoying that a user can't easily change the values... mmmh.

In any case, this is what I have used so far:

```js
const breakpoints = {
  xs: 480,
  sm: 640,
  md: 768,
  lg: 1024,
  xl: 1280,
  "2xl": 1600,
}

const linearClamp = (minWidth, maxWidth, minSize, maxSize) => {
  minWidth = breakpoints[minWidth] ?? parseFloat(minWidth)
  maxWidth = breakpoints[maxWidth] ?? parseFloat(maxWidth)
  minSize = parseFloat(minSize)
  maxSize = parseFloat(maxSize)

  const slope = (maxSize - minSize) / (maxWidth - minWidth)
  const yAxisIntersection = -minWidth * slope + minSize
  const preferredValue = `${yAxisIntersection}rem + ${slope * 100}vw`

  return `clamp(${minSize}rem, ${preferredValue}, ${maxSize}rem)`
}
```

Ideally the breakpoints could be reused from the `--width-*` properties. Any ideas on that?

**Comment by madeleineostoja** [comment]
Thanks for the examples! Yeah I agree that it wouldn't be worth changing how fundamentals like the size and width scales work, it would make Pollen as a whole very complicated for one niche feature. 

I think finding a compromise between 'perfect' fluid units and something straightforward would be the best approach. Sounds like generating defaults with some JS and just giving those to the user could be that compromise. We can reuse variables from config by just stripping units with regex in any js logic needed

**Comment by madeleineostoja** [comment]
As an aside if we did implement this the new `fluid` scale should largely mirror the existing font scale, just tween values based on viewport

**Comment by enyo** [comment]
> As an aside if we did implement this the new fluid scale should largely mirror the existing font scale, just tween values based on viewport

Yes agreed. I think that in general, the font sizes are very typical at about 1024px width, and tend to normalise a bit on smaller devices and "grow apart" on larger devices.

I'm just think about how this could be introduced. Because it doesn't only affect the font sizes, you'd also want the line-heights to be fluid I guess?

So, maybe a very trivial approach would be to add `--fluidline-xs...xl` and `--fluidscale-0...10` (or maybe `--fline` and `--fscale`, or even: `--line-fluidxs` and `--scale-fluid0`)?

Then all these values would be available, and everyone could simply define their `display` and `text` defaults?

**Comment by madeleineostoja** [comment]
Line heights are unitless so I imagine you wouldn't need those to be fluid to maintain a proportionate fluid scale

**Comment by enyo** [comment]
> Line heights are unitless so you wouldn't need those to be fluid to maintain a proportionate fluid scale

That is true, but still line heights change depending on size sometimes. Like in [`heybokeh/design`](https://github.com/heybokeh/design/blob/main/pollen.config.cjs#L29)

But yeah.. maybe that's exaggerated.

**Comment by madeleineostoja** [comment]
They’re just typesets, not bound to viewport sizes

**Comment by enyo** [comment]
Yes, but if you create fluid typesets, then the line heights would possibly be fluid as well, since it's pretty common to reduce the line height for bigger fonts in titles and vice versa. But as I said, that is probably overkill.

If you want, I can start on a PR to introduce some basic fluid scales, and we can continue iterating in a PR?

If so, what naming convention would you go for?

1. `--scale-fluid0`
2. `--scale-0fluid`
3. `--scale-f0`
4. `--scale-0f`
5. `--fluidscale-0`

**Comment by enyo** [comment]
I've started incorporating this in my personal project. I initially thought that the naming convention was not to use dashes in the names of the individual values of the modules, but realised that the colors use them too `--color-blue-500`. So I guess that this makes sense for fluid values as well.

What I then did is to create fluid font scales like this:

```css
--scale-fluid-000: 0.75rem;
--scale-fluid-00: clamp(var(--scale-00), 0.8rem + 0.25vw, var(--scale-0)) /* 30rem -> 80rem */;
--scale-fluid-0: clamp(var(--scale-0), 0.9464285714285714rem + 0.17857142857142858vw, var(--scale-1)) /* 30rem -> 100rem */;
--scale-fluid-1: clamp(var(--scale-1), 1.0714285714285714rem + 0.17857142857142858vw, var(--scale-2)) /* 30rem -> 100rem */;
--scale-fluid-2: clamp(var(--scale-2), 1.1428571428571428rem + 0.35714285714285715vw, var(--scale-3)) /* 30rem -> 100rem */;
--scale-fluid-3: clamp(var(--scale-3), 1.3392857142857142rem + 0.5357142857142857vw, var(--scale-4)) /* 30rem -> 100rem */;
--scale-fluid-4: clamp(var(--scale-4), 1.3928571428571428rem + 1.607142857142857vw, var(--scale-6)) /* 30rem -> 100rem */;
--scale-fluid-5: clamp(var(--scale-6), 2.357142857142857rem + 2.142857142857143vw, var(--scale-8)) /* 30rem -> 100rem */;
--scale-fluid-6: clamp(var(--scale-8), 3rem + 5vw, var(--scale-10)) /* 30rem -> 100rem */;
```

Of course they are generated with a helper function. But I quite like the idea that the fluid scales actually transition from the `--scale-` values. Of course, they are not *really* dynamic, because if you changed `--scale-4` in the browser for example, then it would work insofar as that the max or min value in the clamp function would be correct, but the linear interpolation between the values would be a bit off (meaning: it would either reach the desired value too soon or too late).

So yeah. Not sure what to make of it. It adds quite the complex values so maybe it's just not worth it. It's also possible to just approximate the scaling and just add them manually. So instead of `2.357142857142857rem + 2.142857142857143vw` we could just hard code `2.4rem + 2.2vw`. No complicated generator functions and they scale approximately at the same speed. In my experience though, when resizing the browser window it looks pretty odd when the different sizes reach their "end destination" at different times...

What are your thoughts?

**Comment by madeleineostoja** [comment]
Looks great! I agree it might be worth just hard-coding rounded values, saves a bunch of complexity at (from what I understand) a very minor cost. Can always add a helper function later if people feel it would add value. 

In terms of naming, I think just simple `--fluid-[x]` could be quite nice too. Tradeoff between explicitness and terseness. Would be good to get some feedback from others on naming of it.

And yep the current font size scale assumes a 16px root font size. If someone has changed the root font size (anti pattern to do so these days anyway) that isn't accounted for by Pollen's defaults, and they'd have to define custom scales anyway.

**Comment by enyo** [comment]
Glad you like it!

Yes I agree. After the short discussion with you, I read up on it and came to the same conclusion. It's not even possible to change the default font size in Safari.

I think `--fluid-[x]` sounds good, but it might be confusing that this is referring to fluid font sizes. Because it would/could make sense to also offer fluid pixel sizes (for example, I always like my content paddings to be a bit larger/smaller depending on screen size)

**Comment by enyo** [comment]
To add to this, I think an advantage of using `--scale-fluid-[x]` and `--size-fluid-[x]` would be that they are more easily discoverable.

I was also thinking, whether it would make sense to make them more easily recognisable to actually use the value names as well. So for example, if there is a fluid value from `0` to `1` then it could be: `--scale-fluid-0-1` or even simply `--scale-0-1`. I like this quite a bit, because it's a lot clearer what they represent.
