### ISSUE TITLE
Writing output-file to a file in a directory gives error

### ISSUE THREAD

**Issue by kolben** [heybokeh/pollen#77]
`pollen -o ./dist/pollen.css`

`Error: ENOENT: no such file or directory`

Suggested solution:

Use `fs.mkdir` to create the directory where the output-file is located before writing it

I'll be happy to create a PR :)

**Comment by madeleineostoja** [comment]
Yep happy to accept a PR! Would need a check to for existence of the output dir as well, ie:

```js
if (!fs.existsSync(dir)){
    fs.mkdirSync(dir, { recursive: true });
}
```
