### ISSUE TITLE
postcss and postcss-jit-props integration

### ISSUE THREAD

**Issue by fkrauthan** [heybokeh/pollen#86]
I was wondering if there were ever any thoughts of integrating this with `postcss` and `postcss-jit-props` to remove unused variable definitions from the final project.

This would make the experience as simple as tailwindcss with the benefit of using plain CSS only.

**Comment by madeleineostoja** [comment]
I’d definitely be open to a PR for a bundled postcss plugin, but tbh I think it would be of pretty limited benefit, you’d be trimming a couple of bytes of CSS in most cases. The whole default library weighs a few kb (unlike pre-jIt tailwind) and you can strip modules with one line in config
