### ISSUE TITLE
Not an issue, but information about this project

### ISSUE THREAD

**Issue by carlotm** [heybokeh/pollen#91]
Hi all,
I am considering this project as the main "css framework" for an open source project I have in mind.

Is this project alive and used in production?
I suppose the answer is yes, but just to be sure...

Thank you
Cheers

**Comment by madeleineostoja** [comment]
Hey @carlotm yep I can confirm Pollen is actively maintained and used extensively throughout the [Bokeh](https://bokeh.photo) platform
