### ISSUE TITLE
Stale link to Bokeh on doc site landing page

### ISSUE THREAD

**Issue by andrewcollins** [heybokeh/pollen#92]
heybokeh.com instead of bokeh.photo

Found Pollen via [Lobsters](https://lobste.rs/s/e7srxh/pollen_css_variables_build_system). Is it no longer being developed? I sure like its vibe.

**Comment by madeleineostoja** [comment]
Good catch! Thanks for letting us know :)

Yep Pollen is still actively maintained, it underpins the design system used across the Bokeh ecosystem (dashboard app, portfolio app, and marketing site), as well as several other large production projects.
